name: Comment

on: pull_request
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "{github.head_ref}" --body "Hello ${GITHUB_ACTOR}"
        env: 
            GITHUB_TOKEN: ${{github.token}}
