name: env

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{github.actor}}
    steps:
      - run: echo "${ACTOR}"
      - uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH}}
