name: env

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - run: echo "${GITHUB_ACTOR}"
      - uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH}}

